config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :vehicles
  devise_for :users, controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login', sign_up: 'register' }
  

  resources :contacts, only: %i[new create]
  get 'pages/home'
  get 'pages/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'contacts#new'


end

app/views/shared/_footer.html.erb
<footer class="bg-dark text-light py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h5 class='my-2'>Taller Mecánico El Tuercas</h5>
        <p>Dirección: 123 Calle Principal, Ciudad</p>
        <p>Email: info@tallermecanico.com</p>
        <p>Teléfono: +123 456 789</p>
      </div>
      <div class="col-md-6">
        <h5>Enlaces</h5>
        <ul class="list-unstyled">
          <li>
            <%= link_to 'Inicio', root_path %>
          </li>
          <li>
            <%= link_to 'Sobre nosotros', about_path %>
          </li>
          <li>
            <%= link_to 'Contacto', new_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">🔧 El Tuercas 🔧</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Menú de navegación -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "El Taller Mecánico", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", new_contact_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <%# if is admin print hello world %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Registro Cliente", new_user_registration_path, class: "nav-link ms-3 border border-primary rounded" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Vehículos", vehicles_path, class: "nav-link ms-1 border border-primary rounded" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reparaciones y Servicios", reparations_path, class: "nav-link ms-1 border border-secondary rounded" %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <ul class="navbar-nav">
        <%if user_signed_in?%>
          <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="triggerId" data-bs-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
              <%if current_user.name%>
                Hola <%= current_user.name %>
              <%else%>
                <%= current_user.email %>
              <%end%>
            </button>
            <div class="dropdown-menu" aria-labelledby="triggerId">
              <%# destroy %>
              <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <li>
            <%= link_to 'Iniciar sesión', new_user_session_path, class: 'text-decoration-none text-black' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>