config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :vehicles
  devise_for :users, controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login', sign_up: 'register' }
  

  resources :contacts, only: %i[new create]
  get 'pages/home'
  get 'pages/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'contacts#new'


end

app/views/pages/about.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="display-4">Sobre Nosotros</h1>
      <p class="lead">Taller Mecánico "El Tuercas" es tu destino confiable para servicios de reparación de vehículos en la ciudad. Con años de experiencia en la industria automotriz, nos dedicamos a proporcionar soluciones integrales para mantener tu vehículo en óptimas condiciones.</p>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-lg-6">
      <h2>Nuestros Servicios</h2>
      <p>En "El Tuercas", ofrecemos una amplia gama de servicios de reparación, desde mantenimiento preventivo hasta reparaciones complejas. Nuestros técnicos altamente capacitados están listos para abordar cualquier problema mecánico que pueda surgir en tu vehículo.</p>
      <p>Algunos de nuestros servicios incluyen:</p>
      <ul>
        <li>Servicio de Mantenimiento Regular</li>
        <li>Reparación de Motor y Transmisión</li>
        <li>Reparación de Frenos y Suspensión</li>
        <li>Cambio de Aceite y Filtro</li>
        <li>Diagnóstico Electrónico</li>
        <li>¡Y mucho más!</li>
      </ul>
    </div>
    <div class="col-lg-6">
      <h2>Horarios de Funcionamiento</h2>
      <p>Estamos aquí para servirte en los siguientes horarios:</p>
      <table class="table">
        <tr>
          <td>Días Laborables</td>
          <td>8:00 AM - 6:00 PM</td>
        </tr>
        <tr>
          <td>Sábados</td>
          <td>9:00 AM - 2:00 PM</td>
        </tr>
        <tr>
          <td>Domingos</td>
          <td>Cerrado</td>
        </tr>
      </table>
      <p>¡Visítanos durante nuestros horarios de atención y deja que nuestros expertos cuiden de tu vehículo!</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-lg-6">
      <h1 class="display-4">Bienvenido a Taller Mecánico "El Tuercas"</h1>
      <p class="lead">Tu destino confiable para servicios de reparación de vehículos. Ofrecemos soluciones integrales para mantener tu vehículo en óptimas condiciones.</p>
      <%# button_to contact_path %>
        <%= link_to "Contacto", contact_path, class: "btn btn-primary btn-lg" %>
    </div>
    <div class="col-lg-6">
      <img src="https://picsum.photos/500" class="img-fluid rounded" alt="Taller El Tuercas">
    </div>
  </div>

  <hr class="my-5">

  <div class="row">
    <div class="col-lg-4">
      <h2>Servicios Profesionales</h2>
      <p>Nuestro equipo de técnicos altamente capacitados se dedica a proporcionar servicios de calidad para una variedad de problemas mecánicos y mantenimiento preventivo.</p>
    </div>
    <div class="col-lg-4">
      <h2>Clientes Satisfechos</h2>
      <p>La satisfacción del cliente es nuestra máxima prioridad. Confiar en "El Tuercas" significa confiar en un servicio honesto y confiable para tu vehículo.</p>
    </div>
    <div class="col-lg-4">
      <h2>Contacto</h2>
      <p>Estamos aquí para ayudarte. ¡Contáctanos para programar una cita o hacer cualquier pregunta que puedas tener sobre nuestros servicios!</p>
    </div>
  </div>
</div>