config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :vehicles
  devise_for :users, controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login', sign_up: 'register' }
  

  resources :contacts, only: %i[new create]
  get 'pages/home'
  get 'pages/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'contacts#new'


end

app/models/reparation.rb
# == Schema Information
#
# Table name: reparations
#
#  id          :bigint           not null, primary key
#  vehicle_id  :bigint           not null
#  service_id  :bigint           not null
#  status      :integer          default(0)
#  start_time  :datetime
#  end_time    :datetime
#  observation :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Reparation < ApplicationRecord
  belongs_to :vehicle
  belongs_to :service

  # Validations
  validates :vehicle_id, presence: true
  validates :service_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :status, presence: true

  # Enums
  enum status: { pending: 0, finished: 1}
end

app/controllers/reparations_controller.rb
class ReparationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reparation, only: %i[ show edit update destroy ]

  # GET /reparations or /reparations.json
  def index
    # if user is admin, show all reparations
    if current_user.admin?
      @pagy, @reparations = pagy(Reparation.all)
    else
      # if user is not admin, show only his reparations
      @pagy, @reparations = pagy(Reparation.joins(vehicle: :user).where(users: { id: current_user.id }))
    end
  end
  
  

  # GET /reparations/1 or /reparations/1.json
  def show
  end

  # GET /reparations/new
  def new
    @reparation = Reparation.new
  end

  # GET /reparations/1/edit
  def edit
  end

  # POST /reparations or /reparations.json
  def create
    @reparation = Reparation.new(reparation_params)

    respond_to do |format|
      if @reparation.save
        format.html { redirect_to reparation_url(@reparation), notice: "Reparation was successfully created." }
        format.json { render :show, status: :created, location: @reparation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reparations/1 or /reparations/1.json
  def update
    respond_to do |format|
      if @reparation.update(reparation_params)
        format.html { redirect_to reparation_url(@reparation), notice: "Reparation was successfully updated." }
        format.json { render :show, status: :ok, location: @reparation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reparations/1 or /reparations/1.json
  def destroy
    @reparation.destroy

    respond_to do |format|
      format.html { redirect_to reparations_url, notice: "Reparation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reparation
      @reparation = Reparation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reparation_params
      params.require(:reparation).permit(:vehicle_id, :service_id, :status, :start_time, :end_time, :observation)
    end

end

app/helpers/reparations_helper.rb
module ReparationsHelper
end

app/views/reparations/_form.html.erb
<%= form_with(model: reparation, local: true, class: "mt-4") do |form| %>
  <% if reparation.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(reparation.errors.count, "error") %> prohibited this reparation from being saved:</h2>
      <ul>
        <% reparation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :vehicle_id, class: "form-label" %>
    <%= form.select :vehicle_id, Vehicle.order(:plate).map { |vehicle| [vehicle.plate, vehicle.id] }, { include_blank: false }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :service_id, class: "form-label" %>
    <%= form.select :service_id, Service.all.collect {|service| [service.name, service.id]}, {include_blank: false}, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :status, class: "form-label" %>
    <div class="form-check">
      <%= form.radio_button :status, 'pending', class: "form-check-input" %>
      <%= form.label :status, "Pendiente", class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= form.radio_button :status, "finished", class: "form-check-input" %>
      <%= form.label :status, "Finalizado", class: "form-check-label" %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :start_time, class: "form-label" %>
    <%= form.datetime_field :start_time, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :end_time, class: "form-label" %>
    <%= form.datetime_field :end_time, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :observation, class: "form-label" %>
    <%= form.text_area :observation, class: "form-control", rows: 4 %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reparations/_reparation.html.erb
<div class="col">
</div>
<div class="card bg-light" id="<%= dom_id reparation %>">
  <h5 class="card-header text-center mb-3"><strong>Vehículo (Patente):</strong> <%= reparation.vehicle.plate %></h5>
  <div class="card-body">
    <p class="card-title"><strong>Dueño:</strong> <%= reparation.vehicle.user.name %></p>
    <p class="card-text"><strong>Servicio:</strong> <%= reparation.service.name %></p>
    <p class="card-text"><strong>Ingreso:</strong> <%= reparation.start_time.strftime("%Y/%m/%d %H:%M") %></p>
    <p class="card-text"><strong>Entrega (Estimado):</strong> <%= reparation.end_time.strftime("%Y/%m/%d %H:%M") %></p>
    <p class="card-text"><strong>Observación:</strong> <%= reparation.observation %></p>
    <p class="card-text display-5 text-center"><strong>Estado:</strong> <%= reparation.status %></p>
    <%# reparation.status %>
  </div>
</div>

app/views/reparations/edit.html.erb
<h1>Editing reparation</h1>

<%= render "form", reparation: @reparation %>

<br>

<div>
  <%= link_to "Show this reparation", @reparation %> |
  <%= link_to "Back to reparations", reparations_path %>
</div>

app/views/reparations/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class='mb-5'>Reparaciones y Servicios</h1>
<% if current_user.admin? %>
  <%= link_to "Nueva reparación", new_reparation_path, class:'btn btn-primary' %>
<% end %>
<div class="my-5 row row-cols-1 row-cols-md-3 g-4">
  <% @reparations.each do |reparation|%>
    <div class="col">
      <div class="card text-center bg-light" id="<%= dom_id reparation %>">
        <h5 class="card-header text-center mb-3"><strong>Vehículo (Patente):</strong> <%= reparation.vehicle.plate %></h5>
        <div class="card-body">
          <p class="card-title"><strong>Dueño:</strong> <%= reparation.vehicle.user.name %></p>
          <p class="card-text"><strong>Servicio:</strong> <%= reparation.service.name %></p>
          <p class="card-text"><strong>Ingreso:</strong> <%= reparation.start_time.strftime("%Y/%m/%d %H:%M") %></p>
          <p class="card-text"><strong>Entrega (Estimado):</strong> <%= reparation.end_time.strftime("%Y/%m/%d %H:%M") %></p>
          <p class="card-text"><strong>Observación:</strong> <%= reparation.observation %></p>
          <p>
            <%= link_to "Ver", reparation, class:"btn btn-primary" %>
          </p>
        </div>
        <div class="card-footer">
          <strong>Estado: </strong><%= reparation.status%>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/reparations/new.html.erb
<h1>New reparation</h1>

<%= render "form", reparation: @reparation %>

<br>

<div>
  <%= link_to "Back to reparations", reparations_path %>
</div>

app/views/reparations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reparation %>

<div class="mt-3">

<div class="d-flex justify-content-around">
  <%= button_to "Editar esta reparación", edit_reparation_path(@reparation), method: :get, class: "btn btn-primary" %>
  <%= button_to "Volver a las reparaciones", reparations_path, method: :get, class: "btn btn-secondary" %>
  <%= button_to "Eliminar esta reparación", @reparation, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger"%>
</div>

</div>