config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  resources :vehicles
  devise_for :users, controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login', sign_up: 'register' }
  

  resources :contacts, only: %i[new create]
  get 'pages/home'
  get 'pages/about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'contacts#new'


end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  plate      :string
#  brand      :string
#  model      :string
#  year       :integer
#  color      :string
#  car_issue  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Vehicle < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :reparations, dependent: :destroy
  has_many :services, through: :reparations

  # Validations
  validates :plate, presence: true, uniqueness: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :color, presence: true

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    # if user is admin, show all vehicles
    if current_user.admin?
      # @vehicles = Vehicle.all
      @pagy, @vehicles = pagy(Vehicle.all)
    else
      # if user is not admin, show only his vehicles
      @pagy, @vehicles = pagy(Vehicle.where(user_id: current_user.id))
    end
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:user_id, :plate, :brand, :model, :year, :color, :car_issue)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, class: "mt-4") do |form| %>
  <% if vehicle.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.collection_select :user_id, User.all, :id, :name, { include_blank: "Select User" }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :plate, class: "form-label" %>
    <%= form.text_field :plate, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :brand, class: "form-label" %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :model, class: "form-label" %>
    <%= form.text_field :model, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :year, class: "form-label" %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :color, class: "form-label" %>
    <%= form.text_field :color, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :car_issue, class: "form-label" %>
    <%= form.text_area :car_issue, class: "form-control", rows: 4 %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vehicles/_vehicle.html.erb
<div class="col">
</div>
  <div class="card bg-light" id="<%= dom_id vehicle %>">
    <h5 class="card-header text-center mb-3"><strong>Vehículo (Patente):</strong> <%= vehicle.plate %></h5>
    <div class="card-body">
      <p class="card-title"><strong>Dueño:</strong> <%= vehicle.user.name %></p>
      <p class="card-text"><strong>Marca:</strong> <%= vehicle.brand %></p>
      <p class="card-text"><strong>Modelo:</strong> <%= vehicle.model %></p>
      <p class="card-text"><strong>Año:</strong> <%= vehicle.year %></p>
      <p class="card-text"><strong>Color:</strong> <%= vehicle.color %></p>
      <p class="card-text"><strong>Problema:</strong> <%= vehicle.car_issue %></p>
    </div>
  </div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class='mb-5'>Vehículos</h1>
<%# If admin print "hello world" %>
<% if current_user.admin? %>
  <%= link_to "Enrolar nuevo vehículo", new_vehicle_path, class:'btn btn-primary' %>
<% end %>
<div class="my-5 row row-cols-1 row-cols-md-3 g-4">
  <% @vehicles.each do |vehicle|%>
    <div class="col">
      <div class="card text-center bg-light" id="<%= dom_id vehicle %>">
        <h5 class="card-header text-center mb-3"><strong>Vehículo (Patente):</strong> <%= vehicle.plate %></h5>
        <div class="card-body">
          <p class="card-title"><strong>Dueño:</strong> <%= vehicle.user.name %></p>
          <p class="card-text"><strong>Marca:</strong> <%= vehicle.brand %></p>
          <p class="card-text"><strong>Modelo:</strong> <%= vehicle.model %></p>
          <p class="card-text"><strong>Año:</strong> <%= vehicle.year %></p>
          <p class="card-text"><strong>Color:</strong> <%= vehicle.color %></p>
          <p class="card-text"><strong>Problema:</strong> <%= vehicle.car_issue %></p>
        </div>
        <p>
          <%= link_to "Ver", vehicle, class:"btn btn-primary" %>
        </p>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vehicle %>

<div class="mt-3">

<div class="d-flex justify-content-around">
  <%= button_to "Editar este vehículo", edit_vehicle_path(@vehicle), method: :get, class: "btn btn-primary" %>
  <%= button_to "Volver a los vehículos", vehicles_path, method: :get, class: "btn btn-secondary" %>
  <%= button_to "Eliminar este vehículo", @vehicle, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger"%>

</div>

</div>